# Generated by Django 3.2.18 on 2023-04-14 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230413_1655'),
        ('reviews', '0002_review_score'),
    ]

    operations = [
    ]
