# Generated by Django 3.2.18 on 2023-04-20 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('select1_content', models.CharField(max_length=20)),
                ('select2_content', models.CharField(max_length=20)),
                ('select1_image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='select_image')),
                ('select2_image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='select_image')),
                ('like_users', models.ManyToManyField(related_name='like_posts', to=settings.AUTH_USER_MODEL)),
                ('select1_user', models.ManyToManyField(related_name='select1', to=settings.AUTH_USER_MODEL)),
                ('select2_user', models.ManyToManyField(related_name='select2', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
