# Generated by Django 3.2.18 on 2023-03-31 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountbooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbook',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
