# Generated by Django 3.2.18 on 2023-03-31 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountbooks', '0002_alter_accountbook_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbook',
            name='category',
            field=models.CharField(default='미정', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbook',
            name='date',
            field=models.DateField(default='2023-03-31'),
        ),
        migrations.AlterField(
            model_name='accountbook',
            name='note',
            field=models.CharField(default='미정', max_length=80),
        ),
    ]
