# Generated by Django 3.2.18 on 2023-03-31 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountbooks', '0003_auto_20230331_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbook',
            name='date',
            field=models.DateField(),
        ),
    ]
