# Generated by Django 3.2.18 on 2023-03-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountbooks', '0004_alter_accountbook_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_order', models.BooleanField(default=True)),
                ('note_order', models.BooleanField(default=True)),
                ('category_order', models.BooleanField(default=True)),
                ('amount_order', models.BooleanField(default=True)),
                ('date_order', models.BooleanField(default=True)),
            ],
        ),
    ]
